version: '3.8'

services:
  postgres:
    image: docker.arvancloud.ir/postgres:latest
    container_name: postgres_container
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: todolist
    ports:
      - "5432:5432"
    networks:
      - my_network
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: docker.arvancloud.ir/dpage/pgadmin4
    container_name: pgadmin_container
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin_password
    ports:
      - "8085:80"
    networks:
      - my_network

  laravel:
    build:
      context: ./Back
      dockerfile: Dockerfile
    container_name: react-laravel-back
    environment:
      DB_CONNECTION: pgsql
      DB_HOST: postgres
      DB_PORT: 5432
      DB_DATABASE: todolist
      DB_USERNAME: root
      DB_PASSWORD: root
    ports:
      - "8000:8000"
    networks:
      - my_network
    depends_on:
      - postgres

  react:
    build:
      context: ./Front
      dockerfile: Dockerfile
    container_name: react_container
    ports:
      - "3000:3000"
    networks:
      - my_network

networks:
  my_network:

volumes:
  postgres_data:
